name: KGCT Notifier

on:
  schedule:
    - cron: "*/5 * * * *"     # 5분마다
  workflow_dispatch:

permissions:
  contents: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          DEBUG: "1"
          BOOTSTRAP_ON_START: "0"
        run: python 2notice_bot.py     # ← 여기만 변경!
      
      - name: Commit state if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add state.json || true
            git commit -m "chore: update state.json [skip ci]" || true
            git push
          fi

